### PR TITLE
Add note to use NPM v3

### PR DESCRIPTION
**Pull request by coopy**
Due do NPM2 postinstall bug

### CODE REVIEW

**Comment by boygirl** [comment]
Whelp, that's meta. Travis is failing with `npm 2 + node@v0.12, node@v0.10, and node@v4.2` Can we remove those from our `.travis.yml` with this PR?

**Comment by ryan-roemer** [comment]
@coopy @boygirl -- Sure, but can you ticket "review the situation"? (E.g., consider "don't do `postinstall` somehow which opens up npmv2 again, bugs and all")

**Comment by coopy** [comment]
https://github.com/FormidableLabs/victory/issues/98

**Comment by ryan-roemer** [comment]
Actually, this isn't what we want. Keep the nodes, but remove the NPM3 flag and just _install_ npmv3 -- https://github.com/FormidableLabs/victory/blob/task-addNpmVersionNote/.travis.yml#L24

**Pull request merged**
