### PR TITLE
feat(colorScale): add colorScale property to VictoryChart

### PR DESCRIPTION
**Pull request by 40x**
Addresses #1048 

@boygirl

### CODE REVIEW

**Comment by 40x** [comment]
I think I found an issue. Please hold.

**Comment by 40x** [comment]
Updated

**Comment by boygirl** [comment]
@40x 

I ran our visual tests on these changes, and there are changes related to bar width and colors on nested stacks / groups. There also seems to be an issue with categorical data ordering. 

You can view the build here: https://www.chromaticqa.com/build?appId=5b4acf7c54c0490024d5980b&number=44

Note: several of the changes are left marked as unreviewed because there are only very minor visual changes.

**Comment by boygirl** [comment]
Also, I'm sorry that the visual tests can't be run automatically for external contributors as chromatic requires an app code.

**Comment by 40x** [comment]
I will take a look and get back to you. Thanks for the link to the build.

**Comment by 40x** [comment]
@boygirl sorry for the delay on this, could you please re-run the build? I might have solved some issues but there might be some data related ones that are still not resolved.

**Comment by boygirl** [comment]
@40x sorry for the delay. I'm still seeing visual diffs on your branch, but they don't seem related to your work. I think you may have branched from a commit on master that contained a regression. Could you merge master?

**Comment by boygirl** [comment]
Also, in general, I'm not entirely convinced by this approach. `colorScale` on `VictoryGroup` and `VictoryStack` operates by specifically setting the `stroke` or `fill` of child components. You can find this logic here: https://github.com/FormidableLabs/victory/blob/master/packages/victory-core/src/victory-util/wrapper.js#L227

A more general approach may be to add a `color` prop to each child, and reconcile that prop with other styles. This way, `VictoryChart`, `VictoryGroup`, and `VictoryStack` can just pass a color to their children, and let the child reconcile it with other styles and determine whether to apply it as a stroke or a fill,

**Comment by 40x** [comment]
You are right, let me close this PR and take a look at the changes again.

**Pull request closed without merging**
