### PR TITLE
Bug/build issues

### PR DESCRIPTION
**Pull request by boygirl**
addressing lerna publish errors in latest master

### CODE REVIEW

**Comment by ryan-roemer** [comment]
Hi Lauren! What were the build issues we were running into? I'm curious as to why named exports seem to be at issue and how `default` mega-object export fixes that?

(Generally, we like to steer clear of default export objects that can be individually name-exported directly)

**Comment by boygirl** [comment]
@ryan-roemer this is kind of experimental at this point. Just touching the last thing to change

**Comment by ryan-roemer** [comment]
I may have some time to peek at a build failure if it's just babel / ESM related if you'd like to point me to one (?)

**Comment by boygirl** [comment]
Yep, trying the version command once more. I'll paste the errors here once it finishes. It takes a few minutes

**Comment by boygirl** [comment]
```
lerna ERR! Error: The script called "build-dists" which runs "node ../../node_modules/concurrently/src/main.js --kill-others-on-fail --prefix-colors "bgBlue.bold,bgMagenta.bold" --prefix "[{name}]" --names "build-dist-min,build-dist-dev" 'nps build-dist-min' 'npsbuild-dist-dev'" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.9.3/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 1
lerna ERR! npm ERR! victory-bar@30.6.0 version: `nps build-libs && nps build-dists`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR!
lerna ERR! npm ERR! Failed at the victory-bar@30.6.0 version script.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /Users/boygirl/.npm/_logs/2018-10-27T03_56_52_222Z-debug.log
lerna ERR!
lerna ERR!     at Function.module.exports.sync (/Users/boygirl/.nvm/versions/node/v8.10.0/lib/node_modules/lerna/node_modules/execa/index.js:303:26)
lerna ERR!     at Function.execSync (/Users/boygirl/.nvm/versions/node/v8.10.0/lib/node_modules/lerna/lib/ChildProcessUtilities.js:59:30)
lerna ERR!     at Function.runScriptInDirSync (/Users/boygirl/.nvm/versions/node/v8.10.0/lib/node_modules/lerna/lib/NpmUtilities.js:198:39)
lerna ERR!     at Package.runScriptSync (/Users/boygirl/.nvm/versions/node/v8.10.0/lib/node_modules/lerna/lib/Package.js:95:32)
lerna ERR!     at PublishCommand.runSyncScriptInPackage (/Users/boygirl/.nvm/versions/node/v8.10.0/lib/node_modules/lerna/lib/commands/PublishCommand.js:632:11)
lerna ERR!     at /Users/boygirl/.nvm/versions/node/v8.10.0/lib/node_modules/lerna/lib/commands/PublishCommand.js:681:16
lerna ERR!     at Array.forEach (<anonymous>)
lerna ERR!     at PublishCommand.updateUpdatedPackages (/Users/boygirl/.nvm/versions/node/v8.10.0/lib/node_modules/lerna/lib/commands/PublishCommand.js:660:20)
lerna ERR!     at PublishCommand.execute (/Users/boygirl/.nvm/versions/node/v8.10.0/lib/node_modules/lerna/lib/commands/PublishCommand.js:326:12)
{ Error: The script called "build-dists" which runs "node ../../node_modules/concurrently/src/main.js --kill-others-on-fail --prefix-colors "bgBlue.bold,bgMagenta.bold" --prefix "[{name}]" --names "build-dist-min,build-dist-dev" 'nps build-dist-min' 'nps build-dist-dev'" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.9.3/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! victory-bar@30.6.0 version: `nps build-libs && nps build-dists`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the victory-bar@30.6.0 version script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/boygirl/.npm/_logs/2018-10-27T03_56_52_222Z-debug.log

    at Function.module.exports.sync (/Users/boygirl/.nvm/versions/node/v8.10.0/lib/node_modules/lerna/node_modules/execa/index.js:303:26)
    at Function.execSync (/Users/boygirl/.nvm/versions/node/v8.10.0/lib/node_modules/lerna/lib/ChildProcessUtilities.js:59:30)
    at Function.runScriptInDirSync (/Users/boygirl/.nvm/versions/node/v8.10.0/lib/node_modules/lerna/lib/NpmUtilities.js:198:39)
    at Package.runScriptSync (/Users/boygirl/.nvm/versions/node/v8.10.0/lib/node_modules/lerna/lib/Package.js:95:32)
    at PublishCommand.runSyncScriptInPackage (/Users/boygirl/.nvm/versions/node/v8.10.0/lib/node_modules/lerna/lib/commands/PublishCommand.js:632:11)
    at /Users/boygirl/.nvm/versions/node/v8.10.0/lib/node_modules/lerna/lib/commands/PublishCommand.js:681:16
    at Array.forEach (<anonymous>)
    at PublishCommand.updateUpdatedPackages (/Users/boygirl/.nvm/versions/node/v8.10.0/lib/node_modules/lerna/lib/commands/PublishCommand.js:660:20)
    at PublishCommand.execute (/Users/boygirl/.nvm/versions/node/v8.10.0/lib/node_modules/lerna/lib/commands/PublishCommand.js:326:12)
    at PublishCommand._attempt (/Users/boygirl/.nvm/versions/node/v8.10.0/lib/node_modules/lerna/lib/Command.js:377:21) exitCode: 1}
```

**Comment by boygirl** [comment]
A very unhelpful error.

**Comment by boygirl** [comment]
I've been testing with commit hash `d28b7f0707634e8f8843cbacfc722d581492d684` (before any of the recent changes to VictoryBar) and `nps lerna-dry-run` and that completes without error

**Comment by ryan-roemer** [comment]
I did this on master:

```diff
diff --git a/packages/victory-bar/package.json b/packages/victory-bar/package.json
index bb33f243..76d2cc95 100644
--- a/packages/victory-bar/package.json
+++ b/packages/victory-bar/package.json
@@ -25,7 +25,7 @@
     "victory-core": "^30.3.1"
   },
   "scripts": {
-    "version": "nps build-libs && nps build-dists"
+    "TEMP_version": "nps build-libs && nps build-dists"
   },
   "sideEffects": false
 }
```

so as not to actually _run_ `version` and then running just that command in the single package got a much bigger error (`nps` masks some of this. can look to `lerna exec` on raw babel maybe easier...)

```sh
$ lerna run --scope victory-bar TEMP_version
```

**Comment by boygirl** [comment]
@ryan-roemer thank you, that tactic worked to narrow it down. It was something in the new `VictoryBar` logic. Apparently webpack uglify was choking on the `**` operator, so I replaced with `Math.pow`

**Comment by ryan-roemer** [comment]
Cool! I was playing around a little more and instead of needing to run the `version` command, lerna exec also has the `--scope` thing!

So you can:

```sh
$ lerna exec --scope victory-bar nps build-dists # or
$ lerna exec --scope victory-bar nps build-dist-dev # or
$ lerna exec --scope victory-bar nps build-dist-min # or
```

**Comment by boygirl** [comment]
closing in favor of https://github.com/FormidableLabs/victory/pull/1164

**Pull request closed without merging**
