### PR TITLE
re-formatted themes to use spread operator instead of _.assign

### PR DESCRIPTION
**Pull request by dsm23**

### CODE REVIEW

**Comment by boygirl** [comment]
@dsm23 can you explain the incentive for this change?

It also looks like you're failing CI on some prettier formatting. Would you mind running `nps format` and committing the results?

**Comment by dsm23** [comment]
To reduce the number of lines of code and reduce the dependency on lodash.
I have run the `nps format` command and committed the changes.

**Comment by boygirl** [comment]
@dsm23 `_.assign` is used throughout the codebase, so I don't find this to be a compelling change. Thank you for spending time on Victory anyway!

**Comment by dsm23** [comment]
https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore

**Pull request closed without merging**
