### PR TITLE
Fix VictoryGroup offset with VictoryStack and VictoryBar

### PR DESCRIPTION
**Pull request by cneltyn**
The issue https://github.com/FormidableLabs/victory/issues/1315
The issue can be reproduced in sandbox https://formidable.com/open-source/victory/gallery/stacked-grouped-bars/ just increasing number of stack bars

### CODE REVIEW

**Comment by boygirl** [comment]
@cneltyn Thanks for looking into this! I tried your change locally, and it looks like it's causing some unwanted offset issues:

On master:
Screen Shot 2020-06-07 at 10 51 57 AM

On this branch:
Screen Shot 2020-06-07 at 10 52 23 AM

**Comment by boygirl** [comment]
@cneltyn I created a new PR based on your work that fixes the stacked group issue while maintaining correct offsets for non-stacked groups. I'm going to close this PR in favor of that one, but thank you for the help! I will be sure to credit you in changelog when this work is published.

**Comment by cneltyn** [comment]
@boygirl thanks for the response and the awesome library in general.

**Comment by boygirl** [comment]
Cheers! just pushed this fix as `victory@34.3.10`

**Pull request closed without merging**
