### PR TITLE
Add missing component props from main package

### PR DESCRIPTION
**Pull request by sarah-vanderlaan**
Closes FormidableLabs#1623

### CODE REVIEW

**Comment by sarah-vanderlaan** [comment]
@boygirl hi! Travis is failing with the following error:

```
Chromatic CLI v5.0.0
https://www.chromatic.com/docs/cli
✖ Missing project token
Sign in to https://www.chromatic.com/start and create a new project,
or find your project token on the Manage screen in an existing project.
Set your project token as the CHROMATIC_PROJECT_TOKEN environment variable
or pass the --project-token command line option.
ℹ Read more at https://www.chromatic.com/docs/setup
error Command failed with exit code 254.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Chromatic tests failed. Please investigate
```

Any idea how I can fix this?

**Comment by boygirl** [comment]
@sarah-vanderlaan Thanks for this fix. Unfortunately you wont be able to fix the chromatic error, since it has to do with a authenticating  the service we are using for visual testing, and we can't give away those secrets. It should not fail CI for you, though. I dug into the CI error in this PR, and it looks like it is failing on the step `nps compile-ts`. You should be able to run that command locally from the root directory to see a list of errors. Looks like some duplicate identifiers.

**Comment by sarah-vanderlaan** [comment]
> @sarah-vanderlaan Thanks for this fix. Unfortunately you wont be able to fix the chromatic error, since it has to do with a authenticating the service we are using for visual testing, and we can't give away those secrets. It should not fail CI for you, though. I dug into the CI error in this PR, and it looks like it is failing on the step `nps compile-ts`. You should be able to run that command locally from the root directory to see a list of errors. Looks like some duplicate identifiers.

Thank you @boygirl! I solved the build issues :)

**Comment by boygirl** [comment]
Thanks! I'll release a patch today :)

**Pull request merged**
