### PR TITLE
Fix axes paddings for different orientation options

### PR DESCRIPTION
**Pull request by glvnsky**
Found bug with paddings when axis "orientation" prop is set.
image
The trick is to take padding for axis depend on "orientation" prop if it is set. Also add story for reproduction and check.

### CODE REVIEW

**Comment by glvnsky** [comment]
@boygirl please, take a look.

**Comment by boygirl** [comment]
@glvnsky thank you for this fix. These changes look correct to me. Mind running `nps format` and commiting the results?

**Comment by glvnsky** [comment]
@boygirl updated pull request. Sorry that I missed it. Thank you very much for response and awesome library too :)

**Comment by boygirl** [comment]
Thank you! I'll get a patch released for you this afternoon

**Comment by glvnsky** [comment]
Thanks! I'll do my best in future contributions!

**Pull request merged**
