### PR TITLE
add builder note

### PR DESCRIPTION
**Pull request by knowbody**
- added note about builder (thanks @ryan-roemer).
- removed info about `dist` as we `.gitignore` it now

### CODE REVIEW

**Comment by boygirl** [comment]
:+1: All of the victory repos need this same contrib guide. Is there a way to pull it from the archetype?

**Comment by knowbody** [comment]
yup this is good idea, as if we do any changes to CONTRIBUTING or DEVELOPMENT, etc. we want them to be distributed to all of the repos

**Comment by boygirl** [comment]
This is good to merge now though, imo

**Comment by knowbody** [comment]
ok, let's merge and maybe new issue with: "keep consistent CONTRIBUTING guide across victory components"?

**Pull request merged**
