### PR TITLE
Feature/disable inline styles

### PR DESCRIPTION
**Pull request by tvsmk**
This adds a `disableInlineStyles` prop to `Bar` and `VictoryBar`. I'm not sure that the prop on `VictoryBar` does what it should do. Could you point me in the right direction as to where I can pass it down to the `Bar` component?

### CODE REVIEW

**Comment by boygirl** [comment]
@tvsmk when the `disableInlineStyles` prop is present on `VictoryBar`  default styles should be disabled on both the `dataComponent` and `labelComponent` that `VictoryBar` uses. It can let `Bar` and `VictoryLabel` handle actually removing the styles from the elements they render, but it should pass through the `disableInlineStyles` prop to both of them so that they know to do so. This would be handled [here](https://github.com/FormidableLabs/victory/blob/main/packages/victory-bar/src/helper-methods.js#L102) for the prop passed into `Bar`, and [within LabelHelpers.getProp](https://github.com/FormidableLabs/victory/blob/main/packages/victory-bar/src/helper-methods.js#L129) globally for labels. When this prop is true on `VictoryBar`, we can also probably avoid [calculating](https://github.com/FormidableLabs/victory/blob/main/packages/victory-bar/src/helper-methods.js#L28) and [passing on](https://github.com/FormidableLabs/victory/blob/main/packages/victory-bar/src/helper-methods.js#L71) any styles.

**Comment by tvsmk** [comment]
@boygirl Thanks, the most recent commit should do it. Inspecting the storyboard for it shows the bars have no styles set. Please could you give it a check over?

**Comment by boygirl** [comment]
@tvsmk apologies for the delay. This is looking good! I think it's just failing CI on linting. If you run `nps format` it should clean it up. I'd like to carry this change over for all the components, but I understand if you don't want to take that all on yourself. Let me know what you think. If you prefer to only contibute for the changes that effect `VictoryBar` and `VictoryLabel` I will open a feature branch you can merge into instead of main, and we can split the rest of the work out.

**Comment by boygirl** [comment]
@tvsmk totally understandable. Thanks for getting this started. We'll take it from here :)

**Pull request merged**
