### PR TITLE
Rename .jsx files to .js

### PR DESCRIPTION
**Pull request by josectello**
This address the first item on the checklist in #259. 
`victory.js` and `victory.min.js` have subtly changed as a result of the new file extensions and running the tests/running the code locally, but everything appears to work as before.

### CODE REVIEW

**Comment by boygirl** [comment]
@josectello thanks for taking on this chore. Please remove the `dist` files from this PR though. We're only checking those in for releases. Thanks!

**Comment by josectello** [comment]
@boygirl Missed that, will update. Thanks!

**Comment by josectello** [comment]
I'll re-submit another PR. This one is getting a little hairy trying to remove those files in `/dist` from the PR. Sorry for the mess!

**Comment by boygirl** [comment]
no worries :)

**Pull request closed without merging**
