### PR TITLE
Add Prettier to codebase

### PR DESCRIPTION
**Pull request by blainekasten**
todo

### CODE REVIEW

**Comment by boygirl** [comment]
@blainekasten I own a couple reviews to external contributors, so I'd like to wait on getting this in so I don't make big merge conflicts for them

**Comment by boygirl** [comment]
Also, this is failing our linting rules. Can you change the prettier config to use double quotes and leave the parens for arrow functions?

**Comment by blainekasten** [comment]
@boygirl fwiw, we could give them a really easy way to catch up to master if this get's merged. The steps would be something like:

```
> git rebase master -p -x ours
> yarn nps format
```

That would rebase master, and keep changes from their PRs, then after that's completed, run format on their own code so it is valid.

**Comment by blainekasten** [comment]
Closing in favor of #1215

**Pull request closed without merging**
