### PR TITLE
use builder

### PR DESCRIPTION
**Pull request by boygirl**
cc/ @david-davidson 

this PR updates victory to use builder. I want to make sure this wont make your life miserable... 

I was also wondering whether you were going to end up using ecology in this repo, I notice that it isn't being used yet. I’m happy to add in its boilerplate at the same time if so, and clean up its tasks / deps if not as part of this PR

### CODE REVIEW

**Comment by david-davidson** [comment]
@boygirl I wonder if that weird CI problem would be fixed with the newest `builder`?

Aside from that, LGTM! :gem:

**Comment by boygirl** [comment]
unfortunately not. We're held up by this:
https://github.com/FormidableLabs/builder/issues/30

I'll also wait until your docs branch goes in

**Comment by david-davidson** [comment]
@boygirl Good deal. Was gonna do it the other way around (1. builder 2. docs), but that `builder` bug looks like it could be a headache. :(

**Comment by coopy** [comment]
@boygirl I can take this over, and fix alongside with #49. What do you think?

**Comment by boygirl** [comment]
@coopy this should be ready to go in now, I'd rather get it out sooner and come back for #49

**Comment by dandelany** [comment]
Just gave all the commits a once-over per @boygirl 's request... I don't know all the details of how `builder` works yet, but this looks good to me!

**Pull request merged**
