### PR TITLE
TypeScript: fixed broken import

### PR DESCRIPTION
**Pull request by scottrippey**
# What
An import statement incorrectly referenced `victory-core/src`, which caused all source code to try to be compiled.

# TODO
- [ ] Find a way to prevent this from regressions

### CODE REVIEW

**Comment by ryan-roemer** [comment]
@scottrippey https://eslint.org/docs/latest/rules/no-restricted-imports might be what you want?

**Review by gksander — APPROVED** [review]
Great detective work!

**Comment by ryan-roemer** [comment]
@scottrippey I think this will get you there for what you want:

```diff
diff --git a/.eslintrc.js b/.eslintrc.js
index 6b7581fa4..c61fdd79e 100644
--- a/.eslintrc.js
+++ b/.eslintrc.js
@@ -25,6 +25,17 @@ module.exports = {
     "consistent-return": "off", // we're migrating to TS and this is more properly handled there.
     "react/sort-comp": "off",
     "import/no-unresolved": ["error", { ignore: ["victory*"] }],
+    "no-restricted-imports": [
+      "error",
+      {
+        patterns: [
+          {
+            group: ["victory/src", "victory-*/src"],
+            message: "Do not import from victory source files",
+          },
+        ],
+      },
+    ],
     "max-statements": "off",
     complexity: ["error", { max: 16 }],
     "no-magic-numbers": [
diff --git a/stories/victory-tooltip.stories.js b/stories/victory-tooltip.stories.js
index cc613d1b3..4306bd658 100644
--- a/stories/victory-tooltip.stories.js
+++ b/stories/victory-tooltip.stories.js
@@ -3,7 +3,7 @@
 import React from "react";
 import { VictoryBar } from "victory-bar";
 import { VictoryTooltip, Flyout } from "victory-tooltip";
-import { VictoryLabel } from "victory-core/src";
+import { VictoryLabel } from "victory-core/src"; // eslint-disable-line no-restricted-imports
 import { getData, getMixedData } from "./data";
 import styled from "styled-components";
```

**Comment by scottrippey** [comment]
GMTA!  Added `no-restricted-imports` rules.

Here's proof that it catches both `import 'victory-core/src'` and `import 'victory-core/src/index'`:
image

**Comment by wadehammes** [comment]
Nice work, working on my end. Thanks for the fix!

**Pull request merged**
