### PR TITLE
Type export should not be with other exports

### PR DESCRIPTION
**Pull request by khevamann**
This fixes an issue with types throwing an error https://github.com/FormidableLabs/victory/issues/2355

### CODE REVIEW

**Review by scottrippey — APPROVED** [review]

**Comment by scottrippey** [comment]
Sorry for the delay on this, but thank you for making the change!
The new `export { type ... }` syntax is not as well-supported as `export type { ... }` so this is a good improvement.  Thanks!

**Comment by j-mcgregor** [comment]
Thanks for fixing  this, do you know when it will be included in a release? It's blocking my project building. Thanks!

**Comment by scottrippey** [comment]
We will publish this week for sure, just have to fix a publishing issue.

**Comment by j-mcgregor** [comment]
> We will publish this week for sure, just have to fix a publishing issue.

Thanks!

**Comment by scottrippey** [comment]
Published as `36.6.0`!  Thanks for the contributions.

**Pull request merged**
